import type { Account, Location } from './ranking';
export const locations: Location[] = [
  ['world', 'World', null, 'world'],
  ['asia', 'Asia', 'world', 'continent'],
  ['middle-east', 'Middle East', 'asia', 'subregion'],
  ['gcc', 'GCC', 'middle-east', 'subregion'],
  ['uae', 'United Arab Emirates', 'gcc', 'country'],
  ['dubai-emirate', 'Dubai Emirate', 'uae', 'region'],
  ['dubai', 'Dubai', 'dubai-emirate', 'city'],
  ['abu-dhabi', 'Abu Dhabi', 'uae', 'city'],
  ['sharjah', 'Sharjah', 'uae', 'city'],
  ['saudi-arabia', 'Saudi Arabia', 'gcc', 'country'],
  ['riyadh', 'Riyadh', 'saudi-arabia', 'city'],
  ['jeddah', 'Jeddah', 'saudi-arabia', 'city'],
  ['qatar', 'Qatar', 'gcc', 'country'],
  ['doha', 'Doha', 'qatar', 'city'],
  ['kuwait', 'Kuwait', 'gcc', 'country'],
  ['europe', 'Europe', 'world', 'continent'],
  ['uk', 'United Kingdom', 'europe', 'country'],
  ['england', 'England', 'uk', 'region'],
  ['london', 'London', 'england', 'city'],
  ['india', 'India', 'asia', 'country'],
  ['mumbai', 'Mumbai', 'india', 'city'],
  ['north-america', 'North America', 'world', 'continent'],
  ['usa', 'United States', 'north-america', 'country'],
  ['california', 'California', 'usa', 'region'],
  ['los-angeles', 'Los Angeles', 'california', 'city'],
].map(([id, name, parent, type]) => ({
  id: id!,
  slug: id!,
  name: name!,
  parent_id: parent,
  type: type!,
}));
const rows = [
  ['Zayn Atlas', 'zayn.atlas', 'dubai', 'UAE', 92300, 'amber'],
  ['Mira Sol', 'mira.sol', 'dubai', 'UAE', 81000, 'rose'],
  ['Kai Nomad', 'kai.nomad', 'dubai', 'UAE', 65500, 'blue'],
  ['Noor Studio', 'noor.studio', 'abu-dhabi', 'UAE', 42000, 'mint'],
  ['Rami Lens', 'rami.lens', 'dubai', 'UAE', 28900, 'violet'],
  ['Leena Days', 'leena.days', 'sharjah', 'UAE', 17400, 'rose'],
  ['Sami Roams', 'sami.roams', 'riyadh', 'Saudi Arabia', 12700, 'amber'],
  ['Aya Notes', 'aya.notes', 'doha', 'Qatar', 8600, 'mint'],
  ['Omar Frame', 'omar.frame', 'dubai', 'UAE', 4200, 'blue'],
  ['Nia North', 'nia.north', 'london', 'UK', 2100, 'violet'],
  ['Arjun Coast', 'arjun.coast', 'mumbai', 'India', 1700, 'amber'],
  ['Alex Field', 'alex.field', 'los-angeles', 'USA', 1200, 'mint'],
];
export const demoAccounts: Account[] = rows.map((r, i) => ({
  id: `demo-${i + 1}`,
  slug: String(r[1]),
  username: String(r[1]),
  display_name: String(r[0]),
  location_id: String(r[2]),
  city: locations.find((l) => l.id === r[2])!.name,
  country: String(r[3]),
  bio: 'A fictional creator profile for exploring Rally. Discover the places, stories, and everyday moments that inspire us.',
  total_verified_promotion_cents: Number(r[4]),
  first_verified_promotion_at: `2026-01-${String(i + 1).padStart(2, '0')}T00:00:00Z`,
  ownership_status: 'unclaimed',
  account_status: 'approved',
  color: String(r[5]),
  platform_id: 'snapchat',
}));
