-- Generated from lib/domain/geography.ts. Do not edit by hand.
update public.social_accounts set location_id='london' where location_id='england';
update public.social_accounts set location_id='los-angeles' where location_id='california';
update public.locations set parent_id='uk' where parent_id='england';
update public.locations set parent_id='usa' where parent_id='california';
delete from public.locations where id in ('england','california');

insert into public.locations(id,name,slug,type,parent_id) values
('world','World','world','world',null),
('africa','Africa','africa','continent','world'),
('antarctica','Antarctica','antarctica','continent','world'),
('asia','Asia','asia','continent','world'),
('europe','Europe','europe','continent','world'),
('north-america','North America','north-america','continent','world'),
('oceania','Oceania','oceania','continent','world'),
('south-america','South America','south-america','continent','world'),
('region-caribbean','Caribbean','region-caribbean','region','north-america'),
('abw','Aruba','abw','country','region-caribbean'),
('city-abw-oranjestad','Oranjestad','city-abw-oranjestad','city','abw'),
('region-southern-asia','Southern Asia','region-southern-asia','region','asia'),
('afg','Afghanistan','afg','country','region-southern-asia'),
('city-afg-kabul','Kabul','city-afg-kabul','city','afg'),
('region-middle-africa','Middle Africa','region-middle-africa','region','africa'),
('ago','Angola','ago','country','region-middle-africa'),
('city-ago-luanda','Luanda','city-ago-luanda','city','ago'),
('aia','Anguilla','aia','country','region-caribbean'),
('city-aia-the-valley','The Valley','city-aia-the-valley','city','aia'),
('region-northern-europe','Northern Europe','region-northern-europe','region','europe'),
('ala','Åland Islands','ala','country','region-northern-europe'),
('city-ala-mariehamn','Mariehamn','city-ala-mariehamn','city','ala'),
('region-southeast-europe','Southeast Europe','region-southeast-europe','region','europe'),
('alb','Albania','alb','country','region-southeast-europe'),
('city-alb-tirana','Tirana','city-alb-tirana','city','alb'),
('region-southern-europe','Southern Europe','region-southern-europe','region','europe'),
('and','Andorra','and','country','region-southern-europe'),
('city-and-andorra-la-vella','Andorra la Vella','city-and-andorra-la-vella','city','and'),
('middle-east','Middle East','middle-east','region','asia'),
('uae','United Arab Emirates','uae','country','middle-east'),
('city-uae-abu-dhabi','Abu Dhabi','city-uae-abu-dhabi','city','uae'),
('region-south-america','South America','region-south-america','region','south-america'),
('arg','Argentina','arg','country','region-south-america'),
('city-arg-buenos-aires','Buenos Aires','city-arg-buenos-aires','city','arg'),
('arm','Armenia','arm','country','middle-east'),
('city-arm-yerevan','Yerevan','city-arm-yerevan','city','arm'),
('region-polynesia','Polynesia','region-polynesia','region','oceania'),
('asm','American Samoa','asm','country','region-polynesia'),
('city-asm-pago-pago','Pago Pago','city-asm-pago-pago','city','asm'),
('region-antarctica','Antarctica','region-antarctica','region','antarctica'),
('ata','Antarctica','ata','country','region-antarctica'),
('atf','French Southern and Antarctic Lands','atf','country','region-antarctica'),
('city-atf-port-aux-francais','Port-aux-Français','city-atf-port-aux-francais','city','atf'),
('atg','Antigua and Barbuda','atg','country','region-caribbean'),
('city-atg-saint-john-s','Saint John''s','city-atg-saint-john-s','city','atg'),
('region-australia-and-new-zealand','Australia and New Zealand','region-australia-and-new-zealand','region','oceania'),
('aus','Australia','aus','country','region-australia-and-new-zealand'),
('city-aus-canberra','Canberra','city-aus-canberra','city','aus'),
('region-central-europe','Central Europe','region-central-europe','region','europe'),
('aut','Austria','aut','country','region-central-europe'),
('city-aut-vienna','Vienna','city-aut-vienna','city','aut'),
('aze','Azerbaijan','aze','country','middle-east'),
('city-aze-baku','Baku','city-aze-baku','city','aze'),
('region-eastern-africa','Eastern Africa','region-eastern-africa','region','africa'),
('bdi','Burundi','bdi','country','region-eastern-africa'),
('city-bdi-gitega','Gitega','city-bdi-gitega','city','bdi'),
('region-western-europe','Western Europe','region-western-europe','region','europe'),
('bel','Belgium','bel','country','region-western-europe'),
('city-bel-brussels','Brussels','city-bel-brussels','city','bel'),
('region-western-africa','Western Africa','region-western-africa','region','africa'),
('ben','Benin','ben','country','region-western-africa'),
('city-ben-porto-novo','Porto-Novo','city-ben-porto-novo','city','ben'),
('bfa','Burkina Faso','bfa','country','region-western-africa'),
('city-bfa-ouagadougou','Ouagadougou','city-bfa-ouagadougou','city','bfa'),
('bgd','Bangladesh','bgd','country','region-southern-asia'),
('city-bgd-dhaka','Dhaka','city-bgd-dhaka','city','bgd'),
('bgr','Bulgaria','bgr','country','region-southeast-europe'),
('city-bgr-sofia','Sofia','city-bgr-sofia','city','bgr'),
('bhr','Bahrain','bhr','country','middle-east'),
('city-bhr-manama','Manama','city-bhr-manama','city','bhr'),
('bhs','Bahamas','bhs','country','region-caribbean'),
('city-bhs-nassau','Nassau','city-bhs-nassau','city','bhs'),
('bih','Bosnia and Herzegovina','bih','country','region-southeast-europe'),
('city-bih-sarajevo','Sarajevo','city-bih-sarajevo','city','bih'),
('blm','Saint Barthélemy','blm','country','region-caribbean'),
('city-blm-gustavia','Gustavia','city-blm-gustavia','city','blm'),
('shn','Saint Helena, Ascension and Tristan da Cunha','shn','country','region-western-africa'),
('city-shn-jamestown','Jamestown','city-shn-jamestown','city','shn'),
('region-eastern-europe','Eastern Europe','region-eastern-europe','region','europe'),
('blr','Belarus','blr','country','region-eastern-europe'),
('city-blr-minsk','Minsk','city-blr-minsk','city','blr'),
('region-central-america','Central America','region-central-america','region','north-america'),
('blz','Belize','blz','country','region-central-america'),
('city-blz-belmopan','Belmopan','city-blz-belmopan','city','blz'),
('region-north-america','North America','region-north-america','region','north-america'),
('bmu','Bermuda','bmu','country','region-north-america'),
('city-bmu-hamilton','Hamilton','city-bmu-hamilton','city','bmu'),
('bol','Bolivia','bol','country','region-south-america'),
('city-bol-sucre','Sucre','city-bol-sucre','city','bol'),
('bes','Caribbean Netherlands','bes','country','region-caribbean'),
('city-bes-kralendijk','Kralendijk','city-bes-kralendijk','city','bes'),
('city-bes-oranjestad','Oranjestad','city-bes-oranjestad','city','bes'),
('city-bes-the-bottom','The Bottom','city-bes-the-bottom','city','bes'),
('bra','Brazil','bra','country','region-south-america'),
('city-bra-brasilia','Brasília','city-bra-brasilia','city','bra'),
('brb','Barbados','brb','country','region-caribbean'),
('city-brb-bridgetown','Bridgetown','city-brb-bridgetown','city','brb'),
('region-south-eastern-asia','South-Eastern Asia','region-south-eastern-asia','region','asia'),
('brn','Brunei','brn','country','region-south-eastern-asia'),
('city-brn-bandar-seri-begawan','Bandar Seri Begawan','city-brn-bandar-seri-begawan','city','brn'),
('btn','Bhutan','btn','country','region-southern-asia'),
('city-btn-thimphu','Thimphu','city-btn-thimphu','city','btn'),
('bvt','Bouvet Island','bvt','country','region-antarctica'),
('region-southern-africa','Southern Africa','region-southern-africa','region','africa'),
('bwa','Botswana','bwa','country','region-southern-africa'),
('city-bwa-gaborone','Gaborone','city-bwa-gaborone','city','bwa'),
('caf','Central African Republic','caf','country','region-middle-africa'),
('city-caf-bangui','Bangui','city-caf-bangui','city','caf'),
('can','Canada','can','country','region-north-america'),
('city-can-ottawa','Ottawa','city-can-ottawa','city','can'),
('cck','Cocos (Keeling) Islands','cck','country','region-australia-and-new-zealand'),
('city-cck-west-island','West Island','city-cck-west-island','city','cck'),
('che','Switzerland','che','country','region-western-europe'),
('city-che-bern','Bern','city-che-bern','city','che'),
('chl','Chile','chl','country','region-south-america'),
('city-chl-santiago','Santiago','city-chl-santiago','city','chl'),
('region-far-east','Far East','region-far-east','region','asia'),
('chn','China','chn','country','region-far-east'),
('city-chn-beijing','Beijing','city-chn-beijing','city','chn'),
('civ','Ivory Coast','civ','country','region-western-africa'),
('city-civ-yamoussoukro','Yamoussoukro','city-civ-yamoussoukro','city','civ'),
('cmr','Cameroon','cmr','country','region-middle-africa'),
('city-cmr-yaounde','Yaoundé','city-cmr-yaounde','city','cmr'),
('cod','DR Congo','cod','country','region-middle-africa'),
('city-cod-kinshasa','Kinshasa','city-cod-kinshasa','city','cod'),
('cog','Republic of the Congo','cog','country','region-middle-africa'),
('city-cog-brazzaville','Brazzaville','city-cog-brazzaville','city','cog'),
('cok','Cook Islands','cok','country','region-polynesia'),
('city-cok-avarua','Avarua','city-cok-avarua','city','cok'),
('col','Colombia','col','country','region-south-america'),
('city-col-bogota','Bogotá','city-col-bogota','city','col'),
('com','Comoros','com','country','region-eastern-africa'),
('city-com-moroni','Moroni','city-com-moroni','city','com'),
('cpv','Cape Verde','cpv','country','region-western-africa'),
('city-cpv-praia','Praia','city-cpv-praia','city','cpv'),
('cri','Costa Rica','cri','country','region-central-america'),
('city-cri-san-jose','San José','city-cri-san-jose','city','cri'),
('cub','Cuba','cub','country','region-caribbean'),
('city-cub-havana','Havana','city-cub-havana','city','cub'),
('cuw','Curaçao','cuw','country','region-caribbean'),
('city-cuw-willemstad','Willemstad','city-cuw-willemstad','city','cuw'),
('cxr','Christmas Island','cxr','country','region-australia-and-new-zealand'),
('city-cxr-flying-fish-cove','Flying Fish Cove','city-cxr-flying-fish-cove','city','cxr'),
('cym','Cayman Islands','cym','country','region-caribbean'),
('city-cym-george-town','George Town','city-cym-george-town','city','cym'),
('cyp','Cyprus','cyp','country','region-southern-europe'),
('city-cyp-nicosia','Nicosia','city-cyp-nicosia','city','cyp'),
('cze','Czechia','cze','country','region-central-europe'),
('city-cze-prague','Prague','city-cze-prague','city','cze'),
('deu','Germany','deu','country','region-western-europe')
on conflict(id) do update set
  name=excluded.name,
  slug=excluded.slug,
  type=excluded.type,
  parent_id=excluded.parent_id,
  enabled=true;

insert into public.locations(id,name,slug,type,parent_id) values
('city-deu-berlin','Berlin','city-deu-berlin','city','deu'),
('dji','Djibouti','dji','country','region-eastern-africa'),
('city-dji-djibouti','Djibouti','city-dji-djibouti','city','dji'),
('dma','Dominica','dma','country','region-caribbean'),
('city-dma-roseau','Roseau','city-dma-roseau','city','dma'),
('dnk','Denmark','dnk','country','region-northern-europe'),
('city-dnk-copenhagen','Copenhagen','city-dnk-copenhagen','city','dnk'),
('dom','Dominican Republic','dom','country','region-caribbean'),
('city-dom-santo-domingo','Santo Domingo','city-dom-santo-domingo','city','dom'),
('region-northern-africa','Northern Africa','region-northern-africa','region','africa'),
('dza','Algeria','dza','country','region-northern-africa'),
('city-dza-algiers','Algiers','city-dza-algiers','city','dza'),
('ecu','Ecuador','ecu','country','region-south-america'),
('city-ecu-quito','Quito','city-ecu-quito','city','ecu'),
('egy','Egypt','egy','country','region-northern-africa'),
('city-egy-cairo','Cairo','city-egy-cairo','city','egy'),
('eri','Eritrea','eri','country','region-eastern-africa'),
('city-eri-asmara','Asmara','city-eri-asmara','city','eri'),
('esh','Western Sahara','esh','country','region-northern-africa'),
('city-esh-el-aaiun','El Aaiún','city-esh-el-aaiun','city','esh'),
('esp','Spain','esp','country','region-southern-europe'),
('city-esp-madrid','Madrid','city-esp-madrid','city','esp'),
('est','Estonia','est','country','region-northern-europe'),
('city-est-tallinn','Tallinn','city-est-tallinn','city','est'),
('eth','Ethiopia','eth','country','region-eastern-africa'),
('city-eth-addis-ababa','Addis Ababa','city-eth-addis-ababa','city','eth'),
('fin','Finland','fin','country','region-northern-europe'),
('city-fin-helsinki','Helsinki','city-fin-helsinki','city','fin'),
('region-melanesia','Melanesia','region-melanesia','region','oceania'),
('fji','Fiji','fji','country','region-melanesia'),
('city-fji-suva','Suva','city-fji-suva','city','fji'),
('flk','Falkland Islands','flk','country','region-south-america'),
('city-flk-stanley','Stanley','city-flk-stanley','city','flk'),
('fra','France','fra','country','region-western-europe'),
('city-fra-paris','Paris','city-fra-paris','city','fra'),
('fro','Faroe Islands','fro','country','region-northern-europe'),
('city-fro-torshavn','Tórshavn','city-fro-torshavn','city','fro'),
('region-micronesia','Micronesia','region-micronesia','region','oceania'),
('fsm','Micronesia','fsm','country','region-micronesia'),
('city-fsm-palikir','Palikir','city-fsm-palikir','city','fsm'),
('gab','Gabon','gab','country','region-middle-africa'),
('city-gab-libreville','Libreville','city-gab-libreville','city','gab'),
('uk','United Kingdom','uk','country','region-northern-europe'),
('city-uk-london','London','city-uk-london','city','uk'),
('geo','Georgia','geo','country','middle-east'),
('city-geo-tbilisi','Tbilisi','city-geo-tbilisi','city','geo'),
('ggy','Guernsey','ggy','country','region-northern-europe'),
('city-ggy-st-peter-port','St. Peter Port','city-ggy-st-peter-port','city','ggy'),
('gha','Ghana','gha','country','region-western-africa'),
('city-gha-accra','Accra','city-gha-accra','city','gha'),
('gib','Gibraltar','gib','country','region-southern-europe'),
('city-gib-gibraltar','Gibraltar','city-gib-gibraltar','city','gib'),
('gin','Guinea','gin','country','region-western-africa'),
('city-gin-conakry','Conakry','city-gin-conakry','city','gin'),
('glp','Guadeloupe','glp','country','region-caribbean'),
('city-glp-basse-terre','Basse-Terre','city-glp-basse-terre','city','glp'),
('gmb','Gambia','gmb','country','region-western-africa'),
('city-gmb-banjul','Banjul','city-gmb-banjul','city','gmb'),
('gnb','Guinea-Bissau','gnb','country','region-western-africa'),
('city-gnb-bissau','Bissau','city-gnb-bissau','city','gnb'),
('gnq','Equatorial Guinea','gnq','country','region-middle-africa'),
('city-gnq-malabo','Malabo','city-gnq-malabo','city','gnq'),
('grc','Greece','grc','country','region-southern-europe'),
('city-grc-athens','Athens','city-grc-athens','city','grc'),
('grd','Grenada','grd','country','region-caribbean'),
('city-grd-st-george-s','St. George''s','city-grd-st-george-s','city','grd'),
('grl','Greenland','grl','country','region-north-america'),
('city-grl-nuuk','Nuuk','city-grl-nuuk','city','grl'),
('gtm','Guatemala','gtm','country','region-central-america'),
('city-gtm-guatemala-city','Guatemala City','city-gtm-guatemala-city','city','gtm'),
('guf','French Guiana','guf','country','region-south-america'),
('city-guf-cayenne','Cayenne','city-guf-cayenne','city','guf'),
('gum','Guam','gum','country','region-micronesia'),
('city-gum-hagatna','Hagåtña','city-gum-hagatna','city','gum'),
('guy','Guyana','guy','country','region-south-america'),
('city-guy-georgetown','Georgetown','city-guy-georgetown','city','guy'),
('hkg','Hong Kong','hkg','country','region-far-east'),
('city-hkg-city-of-victoria','City of Victoria','city-hkg-city-of-victoria','city','hkg'),
('hmd','Heard Island and McDonald Islands','hmd','country','region-antarctica'),
('hnd','Honduras','hnd','country','region-central-america'),
('city-hnd-tegucigalpa','Tegucigalpa','city-hnd-tegucigalpa','city','hnd'),
('hrv','Croatia','hrv','country','region-southeast-europe'),
('city-hrv-zagreb','Zagreb','city-hrv-zagreb','city','hrv'),
('hti','Haiti','hti','country','region-caribbean'),
('city-hti-port-au-prince','Port-au-Prince','city-hti-port-au-prince','city','hti'),
('hun','Hungary','hun','country','region-central-europe'),
('city-hun-budapest','Budapest','city-hun-budapest','city','hun'),
('idn','Indonesia','idn','country','region-south-eastern-asia'),
('city-idn-jakarta','Jakarta','city-idn-jakarta','city','idn'),
('imn','Isle of Man','imn','country','region-northern-europe'),
('city-imn-douglas','Douglas','city-imn-douglas','city','imn'),
('india','India','india','country','region-southern-asia'),
('city-india-new-delhi','New Delhi','city-india-new-delhi','city','india'),
('iot','British Indian Ocean Territory','iot','country','region-eastern-africa'),
('city-iot-diego-garcia','Diego Garcia','city-iot-diego-garcia','city','iot'),
('irl','Ireland','irl','country','region-northern-europe'),
('city-irl-dublin','Dublin','city-irl-dublin','city','irl'),
('irn','Iran','irn','country','region-southern-asia'),
('city-irn-tehran','Tehran','city-irn-tehran','city','irn'),
('irq','Iraq','irq','country','middle-east'),
('city-irq-baghdad','Baghdad','city-irq-baghdad','city','irq'),
('isl','Iceland','isl','country','region-northern-europe'),
('city-isl-reykjavik','Reykjavik','city-isl-reykjavik','city','isl'),
('isr','Israel','isr','country','middle-east'),
('city-isr-jerusalem','Jerusalem','city-isr-jerusalem','city','isr'),
('ita','Italy','ita','country','region-southern-europe'),
('city-ita-rome','Rome','city-ita-rome','city','ita'),
('jam','Jamaica','jam','country','region-caribbean'),
('city-jam-kingston','Kingston','city-jam-kingston','city','jam'),
('jey','Jersey','jey','country','region-northern-europe'),
('city-jey-saint-helier','Saint Helier','city-jey-saint-helier','city','jey'),
('jor','Jordan','jor','country','middle-east'),
('city-jor-amman','Amman','city-jor-amman','city','jor'),
('jpn','Japan','jpn','country','region-far-east'),
('city-jpn-tokyo','Tokyo','city-jpn-tokyo','city','jpn'),
('region-central-asia','Central Asia','region-central-asia','region','asia'),
('kaz','Kazakhstan','kaz','country','region-central-asia'),
('city-kaz-astana','Astana','city-kaz-astana','city','kaz'),
('ken','Kenya','ken','country','region-eastern-africa'),
('city-ken-nairobi','Nairobi','city-ken-nairobi','city','ken'),
('kgz','Kyrgyzstan','kgz','country','region-central-asia'),
('city-kgz-bishkek','Bishkek','city-kgz-bishkek','city','kgz'),
('khm','Cambodia','khm','country','region-south-eastern-asia'),
('city-khm-phnom-penh','Phnom Penh','city-khm-phnom-penh','city','khm'),
('kir','Kiribati','kir','country','region-micronesia'),
('city-kir-south-tarawa','South Tarawa','city-kir-south-tarawa','city','kir'),
('kna','Saint Kitts and Nevis','kna','country','region-caribbean'),
('city-kna-basseterre','Basseterre','city-kna-basseterre','city','kna'),
('kor','South Korea','kor','country','region-far-east'),
('city-kor-seoul','Seoul','city-kor-seoul','city','kor'),
('unk','Kosovo','unk','country','region-southeast-europe'),
('city-unk-pristina','Pristina','city-unk-pristina','city','unk'),
('kuwait','Kuwait','kuwait','country','middle-east'),
('city-kuwait-kuwait-city','Kuwait City','city-kuwait-kuwait-city','city','kuwait'),
('lao','Laos','lao','country','region-south-eastern-asia'),
('city-lao-vientiane','Vientiane','city-lao-vientiane','city','lao'),
('lbn','Lebanon','lbn','country','middle-east'),
('city-lbn-beirut','Beirut','city-lbn-beirut','city','lbn'),
('lbr','Liberia','lbr','country','region-western-africa'),
('city-lbr-monrovia','Monrovia','city-lbr-monrovia','city','lbr'),
('lby','Libya','lby','country','region-northern-africa'),
('city-lby-tripoli','Tripoli','city-lby-tripoli','city','lby'),
('lca','Saint Lucia','lca','country','region-caribbean'),
('city-lca-castries','Castries','city-lca-castries','city','lca'),
('lie','Liechtenstein','lie','country','region-western-europe'),
('city-lie-vaduz','Vaduz','city-lie-vaduz','city','lie'),
('lka','Sri Lanka','lka','country','region-southern-asia'),
('city-lka-colombo','Colombo','city-lka-colombo','city','lka'),
('lso','Lesotho','lso','country','region-southern-africa'),
('city-lso-maseru','Maseru','city-lso-maseru','city','lso')
on conflict(id) do update set
  name=excluded.name,
  slug=excluded.slug,
  type=excluded.type,
  parent_id=excluded.parent_id,
  enabled=true;

insert into public.locations(id,name,slug,type,parent_id) values
('ltu','Lithuania','ltu','country','region-northern-europe'),
('city-ltu-vilnius','Vilnius','city-ltu-vilnius','city','ltu'),
('lux','Luxembourg','lux','country','region-western-europe'),
('city-lux-luxembourg','Luxembourg','city-lux-luxembourg','city','lux'),
('lva','Latvia','lva','country','region-northern-europe'),
('city-lva-riga','Riga','city-lva-riga','city','lva'),
('mac','Macau','mac','country','region-far-east'),
('maf','Saint Martin','maf','country','region-caribbean'),
('city-maf-marigot','Marigot','city-maf-marigot','city','maf'),
('mar','Morocco','mar','country','region-northern-africa'),
('city-mar-rabat','Rabat','city-mar-rabat','city','mar'),
('mco','Monaco','mco','country','region-western-europe'),
('city-mco-monaco','Monaco','city-mco-monaco','city','mco'),
('mda','Moldova','mda','country','region-eastern-europe'),
('city-mda-chisinau','Chișinău','city-mda-chisinau','city','mda'),
('mdg','Madagascar','mdg','country','region-eastern-africa'),
('city-mdg-antananarivo','Antananarivo','city-mdg-antananarivo','city','mdg'),
('mdv','Maldives','mdv','country','region-southern-asia'),
('city-mdv-male','Malé','city-mdv-male','city','mdv'),
('mex','Mexico','mex','country','region-north-america'),
('city-mex-mexico-city','Mexico City','city-mex-mexico-city','city','mex'),
('mhl','Marshall Islands','mhl','country','region-micronesia'),
('city-mhl-majuro','Majuro','city-mhl-majuro','city','mhl'),
('mkd','North Macedonia','mkd','country','region-southeast-europe'),
('city-mkd-skopje','Skopje','city-mkd-skopje','city','mkd'),
('mli','Mali','mli','country','region-western-africa'),
('city-mli-bamako','Bamako','city-mli-bamako','city','mli'),
('mlt','Malta','mlt','country','region-southern-europe'),
('city-mlt-valletta','Valletta','city-mlt-valletta','city','mlt'),
('mmr','Myanmar','mmr','country','region-south-eastern-asia'),
('city-mmr-naypyidaw','Naypyidaw','city-mmr-naypyidaw','city','mmr'),
('mne','Montenegro','mne','country','region-southeast-europe'),
('city-mne-podgorica','Podgorica','city-mne-podgorica','city','mne'),
('mng','Mongolia','mng','country','region-far-east'),
('city-mng-ulan-bator','Ulan Bator','city-mng-ulan-bator','city','mng'),
('mnp','Northern Mariana Islands','mnp','country','region-micronesia'),
('city-mnp-saipan','Saipan','city-mnp-saipan','city','mnp'),
('moz','Mozambique','moz','country','region-eastern-africa'),
('city-moz-maputo','Maputo','city-moz-maputo','city','moz'),
('mrt','Mauritania','mrt','country','region-western-africa'),
('city-mrt-nouakchott','Nouakchott','city-mrt-nouakchott','city','mrt'),
('msr','Montserrat','msr','country','region-caribbean'),
('city-msr-plymouth','Plymouth','city-msr-plymouth','city','msr'),
('mtq','Martinique','mtq','country','region-caribbean'),
('city-mtq-fort-de-france','Fort-de-France','city-mtq-fort-de-france','city','mtq'),
('mus','Mauritius','mus','country','region-eastern-africa'),
('city-mus-port-louis','Port Louis','city-mus-port-louis','city','mus'),
('mwi','Malawi','mwi','country','region-eastern-africa'),
('city-mwi-lilongwe','Lilongwe','city-mwi-lilongwe','city','mwi'),
('mys','Malaysia','mys','country','region-south-eastern-asia'),
('city-mys-kuala-lumpur','Kuala Lumpur','city-mys-kuala-lumpur','city','mys'),
('myt','Mayotte','myt','country','region-eastern-africa'),
('city-myt-mamoudzou','Mamoudzou','city-myt-mamoudzou','city','myt'),
('nam','Namibia','nam','country','region-southern-africa'),
('city-nam-windhoek','Windhoek','city-nam-windhoek','city','nam'),
('ncl','New Caledonia','ncl','country','region-melanesia'),
('city-ncl-noumea','Nouméa','city-ncl-noumea','city','ncl'),
('ner','Niger','ner','country','region-western-africa'),
('city-ner-niamey','Niamey','city-ner-niamey','city','ner'),
('nfk','Norfolk Island','nfk','country','region-australia-and-new-zealand'),
('city-nfk-kingston','Kingston','city-nfk-kingston','city','nfk'),
('nga','Nigeria','nga','country','region-western-africa'),
('city-nga-abuja','Abuja','city-nga-abuja','city','nga'),
('nic','Nicaragua','nic','country','region-central-america'),
('city-nic-managua','Managua','city-nic-managua','city','nic'),
('niu','Niue','niu','country','region-polynesia'),
('city-niu-alofi','Alofi','city-niu-alofi','city','niu'),
('nld','Netherlands','nld','country','region-western-europe'),
('city-nld-amsterdam','Amsterdam','city-nld-amsterdam','city','nld'),
('nor','Norway','nor','country','region-northern-europe'),
('city-nor-oslo','Oslo','city-nor-oslo','city','nor'),
('npl','Nepal','npl','country','region-southern-asia'),
('city-npl-kathmandu','Kathmandu','city-npl-kathmandu','city','npl'),
('nru','Nauru','nru','country','region-micronesia'),
('city-nru-yaren','Yaren','city-nru-yaren','city','nru'),
('nzl','New Zealand','nzl','country','region-australia-and-new-zealand'),
('city-nzl-wellington','Wellington','city-nzl-wellington','city','nzl'),
('omn','Oman','omn','country','middle-east'),
('city-omn-muscat','Muscat','city-omn-muscat','city','omn'),
('pak','Pakistan','pak','country','region-southern-asia'),
('city-pak-islamabad','Islamabad','city-pak-islamabad','city','pak'),
('pan','Panama','pan','country','region-central-america'),
('city-pan-panama-city','Panama City','city-pan-panama-city','city','pan'),
('pcn','Pitcairn Islands','pcn','country','region-polynesia'),
('city-pcn-adamstown','Adamstown','city-pcn-adamstown','city','pcn'),
('per','Peru','per','country','region-south-america'),
('city-per-lima','Lima','city-per-lima','city','per'),
('phl','Philippines','phl','country','region-south-eastern-asia'),
('city-phl-manila','Manila','city-phl-manila','city','phl'),
('plw','Palau','plw','country','region-micronesia'),
('city-plw-ngerulmud','Ngerulmud','city-plw-ngerulmud','city','plw'),
('png','Papua New Guinea','png','country','region-melanesia'),
('city-png-port-moresby','Port Moresby','city-png-port-moresby','city','png'),
('pol','Poland','pol','country','region-central-europe'),
('city-pol-warsaw','Warsaw','city-pol-warsaw','city','pol'),
('pri','Puerto Rico','pri','country','region-caribbean'),
('city-pri-san-juan','San Juan','city-pri-san-juan','city','pri'),
('prk','North Korea','prk','country','region-far-east'),
('city-prk-pyongyang','Pyongyang','city-prk-pyongyang','city','prk'),
('prt','Portugal','prt','country','region-southern-europe'),
('city-prt-lisbon','Lisbon','city-prt-lisbon','city','prt'),
('pry','Paraguay','pry','country','region-south-america'),
('city-pry-asuncion','Asunción','city-pry-asuncion','city','pry'),
('pse','Palestine','pse','country','middle-east'),
('city-pse-ramallah','Ramallah','city-pse-ramallah','city','pse'),
('pyf','French Polynesia','pyf','country','region-polynesia'),
('city-pyf-papeete','Papeetē','city-pyf-papeete','city','pyf'),
('qatar','Qatar','qatar','country','middle-east'),
('city-qatar-doha','Doha','city-qatar-doha','city','qatar'),
('reu','Réunion','reu','country','region-eastern-africa'),
('city-reu-saint-denis','Saint-Denis','city-reu-saint-denis','city','reu'),
('rou','Romania','rou','country','region-southeast-europe'),
('city-rou-bucharest','Bucharest','city-rou-bucharest','city','rou'),
('rus','Russia','rus','country','region-eastern-europe'),
('city-rus-moscow','Moscow','city-rus-moscow','city','rus'),
('rwa','Rwanda','rwa','country','region-eastern-africa'),
('city-rwa-kigali','Kigali','city-rwa-kigali','city','rwa'),
('saudi-arabia','Saudi Arabia','saudi-arabia','country','middle-east'),
('city-saudi-arabia-riyadh','Riyadh','city-saudi-arabia-riyadh','city','saudi-arabia'),
('sdn','Sudan','sdn','country','region-northern-africa'),
('city-sdn-khartoum','Khartoum','city-sdn-khartoum','city','sdn'),
('sen','Senegal','sen','country','region-western-africa'),
('city-sen-dakar','Dakar','city-sen-dakar','city','sen'),
('sgp','Singapore','sgp','country','region-south-eastern-asia'),
('city-sgp-singapore','Singapore','city-sgp-singapore','city','sgp'),
('sgs','South Georgia','sgs','country','region-antarctica'),
('city-sgs-king-edward-point','King Edward Point','city-sgs-king-edward-point','city','sgs'),
('sjm','Svalbard and Jan Mayen','sjm','country','region-northern-europe'),
('city-sjm-longyearbyen','Longyearbyen','city-sjm-longyearbyen','city','sjm'),
('slb','Solomon Islands','slb','country','region-melanesia'),
('city-slb-honiara','Honiara','city-slb-honiara','city','slb'),
('sle','Sierra Leone','sle','country','region-western-africa'),
('city-sle-freetown','Freetown','city-sle-freetown','city','sle'),
('slv','El Salvador','slv','country','region-central-america'),
('city-slv-san-salvador','San Salvador','city-slv-san-salvador','city','slv'),
('smr','San Marino','smr','country','region-southern-europe'),
('city-smr-city-of-san-marino','City of San Marino','city-smr-city-of-san-marino','city','smr'),
('som','Somalia','som','country','region-eastern-africa'),
('city-som-mogadishu','Mogadishu','city-som-mogadishu','city','som'),
('spm','Saint Pierre and Miquelon','spm','country','region-north-america'),
('city-spm-saint-pierre','Saint-Pierre','city-spm-saint-pierre','city','spm'),
('srb','Serbia','srb','country','region-southeast-europe'),
('city-srb-belgrade','Belgrade','city-srb-belgrade','city','srb'),
('ssd','South Sudan','ssd','country','region-middle-africa'),
('city-ssd-juba','Juba','city-ssd-juba','city','ssd'),
('stp','São Tomé and Príncipe','stp','country','region-middle-africa'),
('city-stp-sao-tome','São Tomé','city-stp-sao-tome','city','stp'),
('sur','Suriname','sur','country','region-south-america'),
('city-sur-paramaribo','Paramaribo','city-sur-paramaribo','city','sur'),
('svk','Slovakia','svk','country','region-central-europe')
on conflict(id) do update set
  name=excluded.name,
  slug=excluded.slug,
  type=excluded.type,
  parent_id=excluded.parent_id,
  enabled=true;

insert into public.locations(id,name,slug,type,parent_id) values
('city-svk-bratislava','Bratislava','city-svk-bratislava','city','svk'),
('svn','Slovenia','svn','country','region-central-europe'),
('city-svn-ljubljana','Ljubljana','city-svn-ljubljana','city','svn'),
('swe','Sweden','swe','country','region-northern-europe'),
('city-swe-stockholm','Stockholm','city-swe-stockholm','city','swe'),
('swz','Eswatini','swz','country','region-southern-africa'),
('city-swz-lobamba','Lobamba','city-swz-lobamba','city','swz'),
('sxm','Sint Maarten','sxm','country','region-caribbean'),
('city-sxm-philipsburg','Philipsburg','city-sxm-philipsburg','city','sxm'),
('syc','Seychelles','syc','country','region-eastern-africa'),
('city-syc-victoria','Victoria','city-syc-victoria','city','syc'),
('syr','Syria','syr','country','middle-east'),
('city-syr-damascus','Damascus','city-syr-damascus','city','syr'),
('tca','Turks and Caicos Islands','tca','country','region-caribbean'),
('city-tca-cockburn-town','Cockburn Town','city-tca-cockburn-town','city','tca'),
('tcd','Chad','tcd','country','region-middle-africa'),
('city-tcd-n-djamena','N''Djamena','city-tcd-n-djamena','city','tcd'),
('tgo','Togo','tgo','country','region-western-africa'),
('city-tgo-lome','Lomé','city-tgo-lome','city','tgo'),
('tha','Thailand','tha','country','region-south-eastern-asia'),
('city-tha-bangkok','Bangkok','city-tha-bangkok','city','tha'),
('tjk','Tajikistan','tjk','country','region-central-asia'),
('city-tjk-dushanbe','Dushanbe','city-tjk-dushanbe','city','tjk'),
('tkl','Tokelau','tkl','country','region-polynesia'),
('city-tkl-fakaofo','Fakaofo','city-tkl-fakaofo','city','tkl'),
('tkm','Turkmenistan','tkm','country','region-central-asia'),
('city-tkm-ashgabat','Ashgabat','city-tkm-ashgabat','city','tkm'),
('tls','Timor-Leste','tls','country','region-south-eastern-asia'),
('city-tls-dili','Dili','city-tls-dili','city','tls'),
('ton','Tonga','ton','country','region-polynesia'),
('city-ton-nuku-alofa','Nuku''alofa','city-ton-nuku-alofa','city','ton'),
('tto','Trinidad and Tobago','tto','country','region-caribbean'),
('city-tto-port-of-spain','Port of Spain','city-tto-port-of-spain','city','tto'),
('tun','Tunisia','tun','country','region-northern-africa'),
('city-tun-tunis','Tunis','city-tun-tunis','city','tun'),
('tur','Türkiye','tur','country','middle-east'),
('city-tur-ankara','Ankara','city-tur-ankara','city','tur'),
('tuv','Tuvalu','tuv','country','region-polynesia'),
('city-tuv-funafuti','Funafuti','city-tuv-funafuti','city','tuv'),
('twn','Taiwan','twn','country','region-far-east'),
('city-twn-taipei','Taipei','city-twn-taipei','city','twn'),
('tza','Tanzania','tza','country','region-eastern-africa'),
('city-tza-dodoma','Dodoma','city-tza-dodoma','city','tza'),
('uga','Uganda','uga','country','region-eastern-africa'),
('city-uga-kampala','Kampala','city-uga-kampala','city','uga'),
('ukr','Ukraine','ukr','country','region-eastern-europe'),
('city-ukr-kyiv','Kyiv','city-ukr-kyiv','city','ukr'),
('umi','United States Minor Outlying Islands','umi','country','region-north-america'),
('ury','Uruguay','ury','country','region-south-america'),
('city-ury-montevideo','Montevideo','city-ury-montevideo','city','ury'),
('usa','United States','usa','country','region-north-america'),
('city-usa-washington-d-c','Washington D.C.','city-usa-washington-d-c','city','usa'),
('uzb','Uzbekistan','uzb','country','region-central-asia'),
('city-uzb-tashkent','Tashkent','city-uzb-tashkent','city','uzb'),
('vat','Vatican City','vat','country','region-southern-europe'),
('city-vat-vatican-city','Vatican City','city-vat-vatican-city','city','vat'),
('vct','Saint Vincent and the Grenadines','vct','country','region-caribbean'),
('city-vct-kingstown','Kingstown','city-vct-kingstown','city','vct'),
('ven','Venezuela','ven','country','region-south-america'),
('city-ven-caracas','Caracas','city-ven-caracas','city','ven'),
('vgb','British Virgin Islands','vgb','country','region-caribbean'),
('city-vgb-road-town','Road Town','city-vgb-road-town','city','vgb'),
('vir','United States Virgin Islands','vir','country','region-caribbean'),
('city-vir-charlotte-amalie','Charlotte Amalie','city-vir-charlotte-amalie','city','vir'),
('vnm','Vietnam','vnm','country','region-south-eastern-asia'),
('city-vnm-hanoi','Hanoi','city-vnm-hanoi','city','vnm'),
('vut','Vanuatu','vut','country','region-melanesia'),
('city-vut-port-vila','Port Vila','city-vut-port-vila','city','vut'),
('wlf','Wallis and Futuna','wlf','country','region-polynesia'),
('city-wlf-mata-utu','Mata-Utu','city-wlf-mata-utu','city','wlf'),
('wsm','Samoa','wsm','country','region-polynesia'),
('city-wsm-apia','Apia','city-wsm-apia','city','wsm'),
('yem','Yemen','yem','country','middle-east'),
('city-yem-sana-a','Sana''a','city-yem-sana-a','city','yem'),
('zaf','South Africa','zaf','country','region-southern-africa'),
('city-zaf-pretoria','Pretoria','city-zaf-pretoria','city','zaf'),
('city-zaf-bloemfontein','Bloemfontein','city-zaf-bloemfontein','city','zaf'),
('city-zaf-cape-town','Cape Town','city-zaf-cape-town','city','zaf'),
('zmb','Zambia','zmb','country','region-eastern-africa'),
('city-zmb-lusaka','Lusaka','city-zmb-lusaka','city','zmb'),
('zwe','Zimbabwe','zwe','country','region-eastern-africa'),
('city-zwe-harare','Harare','city-zwe-harare','city','zwe'),
('dubai','Dubai','dubai','city','uae'),
('abu-dhabi','Abu Dhabi','abu-dhabi','city','uae'),
('sharjah','Sharjah','sharjah','city','uae'),
('riyadh','Riyadh','riyadh','city','saudi-arabia'),
('jeddah','Jeddah','jeddah','city','saudi-arabia'),
('doha','Doha','doha','city','qatar'),
('kuwait-city','Kuwait City','kuwait-city','city','kuwait'),
('mumbai','Mumbai','mumbai','city','india'),
('los-angeles','Los Angeles','los-angeles','city','usa'),
('new-york-city','New York City','new-york-city','city','usa'),
('san-francisco','San Francisco','san-francisco','city','usa'),
('toronto','Toronto','toronto','city','can'),
('vancouver','Vancouver','vancouver','city','can'),
('sao-paulo','São Paulo','sao-paulo','city','bra'),
('rio-de-janeiro','Rio de Janeiro','rio-de-janeiro','city','bra'),
('sydney','Sydney','sydney','city','aus'),
('melbourne','Melbourne','melbourne','city','aus'),
('auckland','Auckland','auckland','city','nzl'),
('shanghai','Shanghai','shanghai','city','chn'),
('hong-kong','Hong Kong','hong-kong','city','hkg'),
('osaka','Osaka','osaka','city','jpn'),
('singapore','Singapore','singapore','city','sgp'),
('istanbul','Istanbul','istanbul','city','tur'),
('paris','Paris','paris','city','fra'),
('berlin','Berlin','berlin','city','deu'),
('madrid','Madrid','madrid','city','esp'),
('barcelona','Barcelona','barcelona','city','esp'),
('milan','Milan','milan','city','ita'),
('amsterdam','Amsterdam','amsterdam','city','nld'),
('london','London','london','city','uk'),
('manchester','Manchester','manchester','city','uk'),
('cairo','Cairo','cairo','city','egy'),
('lagos','Lagos','lagos','city','nga'),
('cape-town','Cape Town','cape-town','city','zaf'),
('johannesburg','Johannesburg','johannesburg','city','zaf')
on conflict(id) do update set
  name=excluded.name,
  slug=excluded.slug,
  type=excluded.type,
  parent_id=excluded.parent_id,
  enabled=true;
